server:
  port: 80

spring:
  application:
    name: bot-gateway
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:192.168.1.13}:${NACOS_APPLICATION_PORT:8848}
      username: nacos
      password: nacos
    loadbalancer:
      ribbon:
        enabled: false


    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedHeaders: "*"
            allowedOrigins: "*"
            allowedMethods:
              - GET
                POST
                DELETE
                PUT
                OPTION
      routes:
      - id: bot-request
        uri: lb://bot-request
        predicates:
          - Path=/bot/request/**

      - id: bot-auth
        uri: lb://bot-auth
        predicates:
          - Path=/bot/auth/**

      - id: bot-server-rasa
        uri: lb://bot-server
        predicates:
          - Path=/bot/server/**

      - id: bot-server-config
        uri: lb://bot-server
        predicates:
          - Path=/bot/config/**