server:
  port: 8802

spring:
  application:
    name: bot-request
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
    loadbalancer:
      ribbon:
        enabled: false